module.exports = {
	defaultSettings: {
		prefix: '?',
		guildcolor: '',
		guildid: '',
		guildname: '',
		prune: false,
		allownsfw: false,
		audit: false,
		auditchannel: 'Not Set',
		welcome: false,
		welcomechannel: 'Not Set',
		ruleschannel: 'Not Set',
		starchannel: 'Not Set',
		twitterchannel: 'Not Set',
		disabledModules: ['legacy'],
		channels: [],
		twitterwatch: [],
		nsfwblacklist: [],
	},
};
