module.exports = {
	defaultSettings: {
		prefix: '?',
		guildcolor: '',
		guildid: '',
		guildname: '',
		prune: false,
		allownsfw: false,
		audit: false,
		auditchannel: 'Not Set',
		welcome: false,
		welcomechannel: 'Not Set',
		allowinvites: false,
		invitelimit: 10,
		ruleschannel: 'Not Set',
		starchannel: 'Not Set',
		twitterchannel: 'Not Set',
		twitchchannel: 'Not Set',
		twitchmention: false,
		birthdaychannel: 'Not Set',
		levelchannel: 'Not Set',
		disabledModules: ['legacy'],
		channels: [],
		twitterwatch: [],
		nsfwblacklist: [],
	},
};
