module.exports = {
	BotData: require('./botData'),
	Guild: require('./guild'),
	Reaction: require('./reactions'),
	Levelroles: require('./levelroles'),
	Giveaways: require('./giveaways'),
	Birthdays: require('./birthday'),
	TwitchWatch: require('./twitchwatch'),
	Starboard: require('./starboard'),
	userData: require('./userData'),
	Verification: require('./verification'),
	Warning: require('./warnings'),
	Invite: require('./invites'),
	Twitter: require('./twitter'),
	YoutubeLive: require('./youtubelive'),
	TwitchLive: require('./twitchlive'),
};
